#!/bin/bash

# Install Infinity System Monitor

sudo apt update
sudo apt install -y git python3
sudo cd /opt
sudo mkdir the-infinitys
sudo cd the-infinitys
sudo git clone https://github.com/The-Infinitys/task-manager.git system-monitor
sudo cd system-monitor
sudo sh -c ' echo -e "#!/bin/bash\n/opt/the-infinitys/system-monitor/inf-system-monitor"> /usr/local/bin/inf-system-monitor'
sudo chmod 777 /usr/local/bin/inf-system-monitor

echo "Hello, Infinity System Monitor!"
